### ISSUE TITLE
Issue when trying to deploy Sysdig with Terraform and Schematics

### ISSUE THREAD

**Issue by fsgro** [IBM-Cloud/monitoring-sysdig-teams#1]
We are facing an issue when trying to deploy Sysdig using Terraform and schematics.

We are trying to use the content of the following repo https://github.com/IBM-Cloud/monitoring-sysdig-teams in schematics, but we are facing an issue on bash execution (scripts/sysdig-instance-external.sh) when applying plan (cf. sysdig_ws.png - the following attachment)

![sysdig_ws](https://user-images.githubusercontent.com/23315866/82907683-36ea6400-9f67-11ea-9899-977a11d8e6d0.png)

Note that we changed the Terraform required_version to >= 0.12.20 in main.tf.

Is anyone available to resolve the issue in the script?

**Comment by dprosper** [comment]
@fsgro I planned on removing that shell script, it was originally written when there was limited support for Sysdig Teams in the Sysdig Provider for Terraform, however, they have since added that support (https://github.com/draios/terraform-provider-sysdig/issues/11#issuecomment-627208394) and the shell script is no longer necessary nor is it desired.  It might be a ~couple of days~ day for me to get to it and make the updates.

**Comment by dprosper** [comment]
Schematics had not been tested with this repository thus why it was not working.  

This is now resolved with this commit: https://github.com/IBM-Cloud/monitoring-sysdig-teams/commit/840044351cb5311ecc7f9396b7ba1f7db9747764.  In Schematics you will need to pull latest or if you created a fork/copy you will need to bring in the same changes as in that commit. 

I am not able to remove the shell script as of right now, and will be part of another piece of work.

@fsgro Please confirm

**Comment by dprosper** [comment]
nothing else to do this issue was addressed.
